project:
  type: book

execute:
  freeze: auto

book:
  title: "Data Driven Reproducible Study"
  author: "高春辉"
  date: now
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - reproducible-data-analysis-environment.qmd
    - grouped-data-statistical-analysis-and-visualization.qmd
    - transcriptomics-data-analysis-and-visualization.qmd
    - neural-network-from-scratch.qmd
    - pathogen-identification-with-raman-spectroscopy.qmd
    - ai-api-application.qmd
    - machine-learning-algorithms-and-implementation.qmd
    - collaboration-with-global-developers.qmd
    - r-package-development.qmd
    - modern-tools-and-outlook.qmd
    - microbiome-data-analysis-and-visualization.qmd
    - computer-vision-image-analysis.qmd
    - references.qmd

bibliography: references.bib



format:
  html:
    theme: cosmo
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-after-body:
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  pdf:
    documentclass: scrreprt
    mermaid-format: png
    extract-media: images
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-in-header:
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \usepackage[version=4]{mhchem}
            \usepackage{siunitx}
