project:
  type: book

execute:
  freeze: auto

engine: jupyter

book:
  title: "Data Driven Reproducible Study"
  subtitle: "数据驱动的可重复性研究"
  author: "高春辉"
  date: now
  cover-image: cover.png
  repo-url: https://github.com/D2RS-2025spring/data-driven-reproducible-study
  issue-url: https://github.com/D2RS-2025spring/data-driven-reproducible-study/issues/
  repo-actions: [edit, source, issue]
  chapters:
    - index.qmd
    - part: 课程简介
      chapters:
        - intro.qmd
        - what-is-reproducible-study.qmd
    - part: 环境搭建
      chapters:
        - reproducible-data-analysis-environment.qmd
        - setup-a-reproducible-environment.qmd
    - part: 基础知识
      chapters:
        - linux-shell.qmd
        - r-basic.qmd
        - python-basic.qmd
        - python-vs-r.qmd
        - git-basic.qmd
        - literate-programming.qmd
    - part: 分组数据分析
      chapters:
        - grouped-data-analysis.qmd
        - grouped-data-analysis-in-action.qmd
    - part: 转录组数据分析
      chapters:
        - transcriptomics-data-analysis-and-visualization.qmd
        - transcriptomics-data-analysis-in-action.qmd
    - part: 微生物组数据分析
      chapters:
        - microbiome-data-analysis-and-visualization.qmd
    - part: 大模型API调用
      chapters:
        - huggingface.qmd
        - chatanywhere.qmd
        - bailian.qmd
        - deepseek.qmd
    - part: 从零开始神经网络
      chapters:
        - neural-network-from-scratch.qmd
    - part: 机器学习
      chapters:
        - machine-learning-algorithms-and-implementation.qmd
    - part: 拉曼光谱识别病原菌
      chapters:
        - pathogen-identification-with-raman-spectroscopy.qmd
        - bacteria-id-annotation.qmd
        - pretrained-model.qmd
    - part: 计算机视觉分析实验图片
      chapters:
        - computer-vision-image-analysis.qmd
    - part: 开发协作
      chapters:
        - collaboration-with-global-developers.qmd
        - r-package-development.qmd      
    - references.qmd
  appendices:
    - markdown.qmd
    - write-math-equation.qmd
    - quarto-cheatsheet.qmd
    - ggplot2-cheatsheet.qmd
    - dplyr-cheatsheet.qmd

bibliography: [references.bib, packages.bib]



format:
  html:
    theme: cosmo
    fig-width: 7
    fig-asp: 0.618
    fig-align: center
    out-width: 100%
    warning: false
    message: false
    include-after-body:
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  pdf:
    documentclass: scrreprt
    papersize: a4
    margin: 1.5cm
    mermaid-format: png
    extract-media: images
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    out-width: 100%
    include-in-header:
          text: |
            \sloppy
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \usepackage[version=4]{mhchem}
            \usepackage{siunitx}
