project:
  type: book

execute:
  freeze: auto

book:
  title: "Data Driven Reproducible Study"
  author: "高春辉"
  date: now
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: 课程简介
      chapters:
        - intro.qmd
    - part: 环境搭建
      chapters:
        - reproducible-data-analysis-environment.qmd
        - linux-shell.qmd
        - r-basic.qmd
        - python-basic.qmd
        - python-vs-r.qmd
        - modern-tools-and-outlook.qmd
    - part: 数据分析
      chapters:
        - grouped-data-statistical-analysis-and-visualization.qmd
        - grouped-data-analysis-in-action.qmd
        - transcriptomics-data-analysis-and-visualization.qmd
        - microbiome-data-analysis-and-visualization.qmd
    - part: 人工智能
      chapters:
        - neural-network-from-scratch.qmd
        - pathogen-identification-with-raman-spectroscopy.qmd
        - ai-api-application.qmd
        - machine-learning-algorithms-and-implementation.qmd
        - computer-vision-image-analysis.qmd
    - part: 开发协作
      chapters:
        - collaboration-with-global-developers.qmd
        - r-package-development.qmd      
    - references.qmd
  appendices:
    - markdown-syntax.qmd
    - write-math-equation.qmd
    - technical-writing-with-quarto.qmd
    - ggplot2-cheatsheet.qmd

bibliography: references.bib



format:
  html:
    theme: cosmo
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-after-body:
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  pdf:
    documentclass: scrreprt
    mermaid-format: png
    extract-media: images
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-in-header:
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \usepackage[version=4]{mhchem}
            \usepackage{siunitx}
