name: Deploy Quarto Book to gh-pages

on:
  push:
    branches:
      - main  # 触发条件：当推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 确保递归克隆所有子模块
          fetch-depth: 0         # 获取完整的历史记录以支持 renv 和其他工具

      # 设置 Conda 环境
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"  # 显式指定 Miniconda 版本
          python-version: 3.10.16         # 根据需要调整 Python 版本
          activate-environment: data-driven-reproducible-study  # Conda 环境名称
          environment-file: environment.yml  # 如果有环境文件，请指定路径

      # 安装 R 和 renv
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install renv
        run: Rscript -e "install.packages('renv')"

      # 恢复 renv 环境
      - name: Restore R dependencies with renv
        run: Rscript -e "renv::restore()"

      # 安装 Quarto CLI（适用于 macOS）
      - name: Install Quarto CLI
        run: |
          brew install quarto-cli

      # 构建 Quarto Book
      - name: Build Quarto Book
        run: quarto render

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book  # Quarto 默认输出目录为 _book
          commit_message: "Deploy Quarto Book to gh-pages"