name: Deploy Quarto Book to gh-pages

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 确保递归克隆所有子模块
          fetch-depth: 0         # 获取完整的历史记录以支持 renv 和其他工具

      # 设置 Conda 环境
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: "latest"  # 显式指定 Miniconda 版本
          python-version: 3.10.16         # 根据需要调整 Python 版本
          activate-environment: data-driven-reproducible-study  # Conda 环境名称
          environment-file: environment.yml  # 如果有环境文件，请指定路径

      - name: Set CONDA_DEFAULT_ENV
        run: |
          echo "CONDA_DEFAULT_ENV=data-driven-reproducible-study" >> $GITHUB_ENV
          echo "QUARTO_PYTHON=$CONDA/envs/data-driven-reproducible-study/bin/python" >> $GITHUB_ENV
          conda info
          conda list

      # 安装 R 和 renv
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install renv
        run: Rscript -e "install.packages('renv')"

      # 恢复 renv 环境
      - name: Restore R dependencies with renv
        run: Rscript -e "renv::restore()"

      # 安装 Quarto CLI（适用于 macOS）
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 构建 Quarto Book
      - name: Build Quarto Book
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: html


      # 部署到 gh-pages 分支
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target: gh-pages